# Copied from https://github.com/nim-lang/Nim/wiki/TravisCI
language: c
env:
  # Build and test against the master and devel branches of Nim
  - BRANCH=master
  - BRANCH=devel
compiler:
  #- gcc
  - clang
matrix:
  allow_failures:
    # Ignore failures when building against the devel Nim branch
    - env: BRANCH=devel
  fast_finish: true
install:
  - |
    if [ ! -x nim-$BRANCH/bin/nim ]; then
      git clone -b $BRANCH --depth 1 git://github.com/nim-lang/nim nim-$BRANCH/
      cd nim-$BRANCH
      git clone -b $BRANCH --depth 1 git://github.com/nim-lang/csources csources/
      cd csources
      sh build.sh
      cd ..
      rm -rf csources
      bin/nim c koch
      ./koch boot -d:release
    else
      cd nim-$BRANCH
      git fetch origin
      if ! git merge FETCH_HEAD | grep "Already up-to-date"; then
        bin/nim c koch
        ./koch boot -d:release
      fi
    fi
    cd ..
    if [ ! -x nifty/nifty ]; then
      git clone --depth 1 git://github.com/h3rald/nifty nifty/
      nim c --cc:$CC --verbosity:0 -d:release nifty.nim
    fi
before_script:
    - export PATH="nifty:nim-$BRANCH/bin${PATH:+:$PATH}"
script:
    - nifty install
    - nifty build discount
    - nim c --cc:$CC --verbosity:0 -d:discount hastyscribe.nim
    # Optional: build docs.
    #- nim doc --docSeeSrcUrl:https://github.com/h3rald/litestore/blob/master --project litestore.nim
cache:
  directories:
    - nim-master
    - nim-devel
    - nifty
